### ISSUE TITLE
Both 53-coredns.sh and 53-coredns.conflist are empty files

### ISSUE THREAD

**Issue by 5thsymphony** [Kashalls/udmp-utils#1]
Hi, thanks for building this, I see that both these files are blank.

https://github.com/Kashalls/udmp-utils/blob/master/coredns/53-coredns.sh 
https://github.com/Kashalls/udmp-utils/blob/master/coredns/53-coredns.conflist

Can you point me in the right direction to reconstruct them or are you able to upload them?

**Comment by kashalls** [comment]
Whoops, how'd I do that? Let me get them fresh from the udmp tonight.

**Comment by 5thsymphony** [comment]
Thanks I massively appreciate it, I somehow managed to mess up DNSMasq last night when I tried to have a go at making my own version of this project. I was most unpopular when noone could get an IP or resolve DNS queries.

**Comment by kashalls** [comment]
The original files are here: https://github.com/Kashalls/home-cluster/tree/b8120267ed78085b998613b10e61226a4d2c8de2/udmp/coredns

I'll move everything over tonight

**Comment by kashalls** [comment]
https://github.com/Kashalls/udmp-utils/commit/e11612cba9ac923963eb8211f486539da0056edf fixes this. "Totally took me only one night. I swear :)"
